addons:
#  coverity_scan:
#    project:
#      name: "AraHaan/bin2c"
#      version: 0.15.0
#      description: "bin2c Conversion Tool."

    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
        packages:
            - g++-5
            - g++-6

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: COMPILER=g++-5
      - <<: *linux
        env: COMPILER=g++-6
      - <<: *osx
        osx_image: xcode9.2

install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi
  - if [ "$COMPILER" = "g++-5"        ]; then export CXX="g++-5" CC="gcc-5";  fi
  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";  fi
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh